name: 🐧 Linux builds
on:
  workflow_call:
    inputs:
      godot_treeish:
        description: A tag, branch or commit hash in the Godot repository.
        type: string
        default: master
      limboai_treeish:
        description: A tag, branch or commit hash in the LimboAI repository.
        type: string
        default: master

  workflow_dispatch:
    inputs:
      godot_treeish:
        description: A tag, branch or commit hash in the Godot repository.
        type: string
        default: master
      limboai_treeish:
        description: A tag, branch or commit hash in the LimboAI repository.
        type: string
        default: master


# Global Settings
env:
  SCONS_CACHE_LIMIT: 4096
  SCONSFLAGS: production=yes tests=no verbose=yes warnings=extra werror=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  linux-builds:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (x86_64, release)
            target: editor
            arch: x86_64
            build-mono: false

          - name: Template (x86_64, release)
            target: template_release
            arch: x86_64
            build-mono: false

          - name: Template (x86_64, debug)
            target: template_debug
            arch: x86_64
            build-mono: false

          # - name: Editor (x86_32, release)
          #   target: editor
          #   arch: x86_32
          #   build-mono: false

          - name: Template (x86_32, release)
            target: template_release
            arch: x86_32
            build-mono: false

          - name: Template (x86_32, debug)
            target: template_debug
            arch: x86_32
            build-mono: false

          - name: Editor .NET (x86_64, release)
            target: editor
            arch: x86_64
            build-mono: true

          - name: Template .NET (x86_64, release)
            target: template_release
            arch: x86_64
            build-mono: true

          - name: Template .NET (x86_64, debug)
            target: template_debug
            arch: x86_64
            build-mono: true

          # - name: Editor .NET (x86_32, release)
          #   target: editor
          #   arch: x86_32
          #   build-mono: true

          - name: Template .NET (x86_32, release)
            target: template_release
            arch: x86_32
            build-mono: true

          - name: Template .NET (x86_32, debug)
            target: template_debug
            arch: x86_32
            build-mono: true

    env:
      BIN: godot.linuxbsd.${{matrix.target}}.${{matrix.arch}}${{  matrix.build-mono == true && '.mono' || ''  }}

    steps:
      - name: Clone Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot_treeish }}

      - name: Clone LimboAI module
        uses: actions/checkout@v3
        with:
          path: modules/limboai
          ref: ${{ inputs.limboai_treeish }}

      # About sed see: https://github.com/godotengine/buildroot/issues/6
      - name: Set up buildroot x86_64
        if: matrix.arch == 'x86_64'
        run: |
          wget https://download.tuxfamily.org/godotengine/toolchains/linux/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar -xjf x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          mv x86_64-godot-linux-gnu_sdk-buildroot buildroot
          cd buildroot
          sed -i x86_64-godot-linux-gnu/sysroot/usr/lib/pkgconfig/dbus-1.pc -e "s@/lib@/lib64@g"
          ./relocate-sdk.sh
          cd ..

      - name: Set up buildroot x86_32
        if: matrix.arch == 'x86_32'
        run: |
          wget https://download.tuxfamily.org/godotengine/toolchains/linux/i686-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar -xjf i686-godot-linux-gnu_sdk-buildroot.tar.bz2
          mv i686-godot-linux-gnu_sdk-buildroot buildroot
          cd buildroot
          ./relocate-sdk.sh
          cd ..

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{matrix.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{env.BIN}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{env.BIN}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{env.BIN}}-${{env.GODOT_BASE_BRANCH}}

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          PATH=${GITHUB_WORKSPACE}/buildroot/bin:$PATH
          scons platform=linuxbsd target=${{matrix.target}} arch=${{matrix.arch}} module_mono_enabled=${{matrix.build-mono}} ${{env.SCONSFLAGS}}

      - name: Generate C# glue
        if: matrix.build-mono && matrix.target == 'editor'
        run: |
          ./bin/$BIN --headless --generate-mono-glue ./modules/mono/glue || true

      - name: Build .NET solutions
        if: matrix.build-mono && matrix.target == 'editor'
        run: |
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd

      - name: Prepare artifact
        run: |
          strip ./bin/godot.*
          chmod +x ./bin/godot.*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot.limboai.${{matrix.target}}.linux.${{matrix.arch}}${{  matrix.build-mono == true && '.mono' || ''  }}
          path: bin/*
