name: 🐧 Linux Builds
on:
  workflow_call:

  workflow_dispatch:


# Global Settings
env:
  SCONS_CACHE_LIMIT: 4096
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  linux:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (Godot v4.1.1-stable)
            target: editor
            production: yes
            build-mono: false
            godot-treeish: 4.1.1-stable
            executable-file: godot.linuxbsd.editor.x86_64

          # - name: Template (Godot v4.1.1-stable)
          #   target: template_release
          #   production: yes
          #   build-mono: false
          #   godot-treeish: v4.1.1-stable
          #   executable-file: ???

    steps:
      # Clone godot
      - uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          ref: ${{ matrix.godot-treeish }}

      # Clone limboai module
      - uses: actions/checkout@v3
        with:
          path: modules/limboai

      # Setup buildroot
      - name: Setup buildroot
        run: |
          wget https://download.tuxfamily.org/godotengine/toolchains/linux/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar -xjf x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          cd x86_64-godot-linux-gnu_sdk-buildroot
          sed -i x86_64-godot-linux-gnu/sysroot/usr/lib/pkgconfig/dbus-1.pc -e "s@/lib@/lib64@g"
          ./relocate-sdk.sh
          cd ..

      # Build step
      - name: Build step
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          PATH=${GITHUB_WORKSPACE}/x86_64-godot-linux-gnu_sdk-buildroot/bin:$PATH
          scons -j2 platform=linuxbsd tests=no target=${{matrix.target}} production=${{matrix.production}}

      # Make build available
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.executable-file}}
          path: bin/${{matrix.executable-file}}

