name: 🪟 Windows builds
on:
  workflow_call:
    inputs:
      godot-treeish:
        description: A tag, branch or commit hash in the Godot repository.
        type: string
        default: master
      limboai-treeish:
        description: A tag, branch or commit hash in the LimboAI repository.
        type: string
        default: master

  workflow_dispatch:
    inputs:
      godot-treeish:
        description: A tag, branch or commit hash in the Godot repository.
        type: string
        default: master
      limboai-treeish:
        description: A tag, branch or commit hash in the LimboAI repository.
        type: string
        default: master

# Global Settings
env:
  SCONS_CACHE_MSVC_CONFIG: true
  SCONS_CACHE_LIMIT: 4096
  SCONSFLAGS: production=yes tests=no verbose=yes warnings=extra werror=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  windows-builds:
    runs-on: "windows-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (x86_64, release)
            target: editor
            arch: x86_64
            build-mono: false

          - name: Template (x86_64, release)
            target: template_release
            arch: x86_64
            build-mono: false

          - name: Template (x86_64, debug)
            target: template_debug
            arch: x86_64
            build-mono: false

          # - name: Editor (x86_32, release)
          #   target: editor
          #   arch: x86_32
          #   build-mono: false

          - name: Template (x86_32, release)
            target: template_release
            arch: x86_32
            build-mono: false

          - name: Template (x86_32, debug)
            target: template_debug
            arch: x86_32
            build-mono: false

          - name: Editor .NET (x86_64, release)
            target: editor
            arch: x86_64
            build-mono: true

          - name: Template .NET (x86_64, release)
            target: template_release
            arch: x86_64
            build-mono: true

          - name: Template .NET (x86_64, debug)
            target: template_debug
            arch: x86_64
            build-mono: true

          # - name: Editor .NET (x86_32, release)
          #   target: editor
          #   arch: x86_32
          #   build-mono: true

          - name: Template .NET (x86_32, release)
            target: template_release
            arch: x86_64
            build-mono: true

          - name: Template .NET (x86_32, debug)
            target: template_debug
            arch: x86_32
            build-mono: true

    env:
      BIN: godot.windows.${{matrix.target}}.${{matrix.arch}}${{  matrix.build-mono == true && '.mono' || ''  }}

    steps:
      - name: Clone Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot-treeish }}

      - name: Clone LimboAI module
        uses: actions/checkout@v3
        with:
          path: modules/limboai
          ref: ${{ inputs.limboai-treeish }}

      # Inits GODOT_VERSION, LIMBOAI_VERSION and NAME_PREFIX environment variables.
      - uses: ./modules/limboai/.github/actions/init-version

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Set up scons
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons==4.4.0
          python --version
          scons --version

      - name: Set up MSVC problem matcher
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Set up scons cache
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{matrix.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{env.BIN}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{env.BIN}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{env.BIN}}-${{env.GODOT_BASE_BRANCH}}

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons -j2 platform=windows target=${{matrix.target}} arch=${{matrix.arch}} module_mono_enabled=${{matrix.build-mono}} ${{env.SCONSFLAGS}}

      - name: Generate C# glue
        if: matrix.build-mono && matrix.target == 'editor'
        env:
          GODOT_VERSION_STATUS: limboai
        run: |
          ./bin/${{ env.BIN }} --headless --generate-mono-glue ./modules/mono/glue || true

      - name: Build .NET solutions
        if: matrix.build-mono && matrix.target == 'editor'
        env:
          GODOT_VERSION_STATUS: limboai
        run: |
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=windows

      - name: Prepare artifact
        shell: bash
        env:
          OUTDIR: ${{ startsWith(matrix.target, 'template') && 'out/templates' || 'out/' }}
        run: |
          rm -f bin/*.{exp,lib,pdb}
          mkdir -p out/templates/
          mv bin/* ${{env.OUTDIR}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        env:
          NAME_EDITOR: ${{env.NAME_PREFIX}}.${{matrix.target}}.windows.${{matrix.arch}}${{  matrix.build-mono == true && '.mono' || ''  }}
          NAME_TEMPLATES: ${{env.NAME_PREFIX}}.export-templates${{  matrix.build-mono == true && '.mono' || ''  }}
        with:
          name: ${{ startsWith(matrix.target, 'template') && env.NAME_TEMPLATES || env.NAME_EDITOR  }}
          path: out/*
